name: Publish to JSR
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Get Dependencies
        run: pnpm install
      - name: Publish package
        run: pnpx jsr publish
